package bg.kirilov.timer.ui;

import bg.kirilov.timer.presenter.CalculatingPerSecondView;
import bg.kirilov.timer.presenter.Formatters;
import bg.kirilov.timer.presenter.TickingPresenter;

import javax.swing.*;

/**
 * JPanel that contains a clock that measures the time and calculates
 * the amount that a meeting costs a number of participants due to a
 * pay rate per hour. Not connected with any currency.<br>
 * <br>
 * The input is provided in two text fields and it's verified when the START
 * button is clicked. When a session is ended - the data in the text fields is
 * reset.<br>
 * <br>
 * TickingViewImpl contains means to pause the clock and display results page when
 * wanted by the user. The execution of the clock creates and starts a new thread.<br>
 * <br>
 * All operations are thread-safe since they are never meant to be executed by
 * more than one CalculatingPerSecondThread-clock.
 *
 * @author Leni Kirilov
 * @version 2010-February
 */
public class TickingViewImpl extends javax.swing.JPanel implements CalculatingPerSecondView, TickingView {

    //TODO TEMP variable for saver and easier refactoring. Remove when refactoring is done
    public TickingPresenter presenter;

    public TickingViewImpl() {
        initComponents();
        pauseButton.setEnabled(false);
    }

    public void setPresenter(TickingPresenter presenter) {
        this.presenter = presenter;
    }

    /**
     * Start the clock ticking. Enables the PAUSE button.
     */
    public void startClock() {
        pauseButton.setEnabled(true);
        startButton.setText("STOP");
    }

    //TODO try to create an ENUM with the states of the panel (in the presenter of course) and try to reduce the boolean variables

    /**
     * Stops the clock. Disables the PAUSE button.
     */
    public void stopClock() {
        pauseButton.setEnabled(false);
        startButton.setText("START");
    }

    //TODO move javadoc to interface
    /**
     * Pauses the clock(clock thread). Changes the label of the PAUSE button.
     */
    public void pauseClock() {
        pauseButton.setText("RESUME");
    }

    /**
     * Resumes clock. Notifies the thread to continue execution.
     */
    public void resumeClock() {
        pauseButton.setText("PAUSE");
    }

    //TODO extract input parsing to another class?

    /**
     * Displays Dialog window to choose from Yes/No if abortion is wanted.
     *
     * @return true if clicked YES on the dialog
     */
    private boolean askIfWantToAbort() {
        int result = JOptionPane.showConfirmDialog(this,
                "Are you sure you want to abort the current counting?",
                "Abort ?",
                JOptionPane.YES_NO_OPTION);

        return (result == JOptionPane.YES_OPTION) ? true : false;
    }

    /**
     * Displays dialog window to choose Yes/No if results are wanted.
     *
     * @return true if clicked YES on the dialog
     */
    private boolean wantsReport() {
        int result = JOptionPane.showConfirmDialog(this,
                "Do you want to see report for this session?",
                "Report ?",
                JOptionPane.YES_NO_OPTION);

        return (result == JOptionPane.YES_OPTION) ? true : false;
    }

    /**
     * Sets pay rate and synchronizes the internals logics with the UI.
     *
     * @param payRate - valid double number
     */
    @Override
    public void setPayRate(double payRate) {
        String text = Formatters.getNumberFormatter().format(payRate);
        payRateTextField.setText(text);
    }

    /**
     * Sets numberOfPeople and synchronizes the internals logics with the UI.
     *
     * @param number - valid integer number
     */
    @Override
    public void setNumberPeople(int number) {
        numberParticipantsTextField.setText(String.valueOf(number));
    }

    /**
     * Turns on/off the input text fields.
     *
     * @param enabled if true, input fields are enabled
     */
    public void setInput(boolean enabled) {
        payRateTextField.setEnabled(enabled);
        numberParticipantsTextField.setEnabled(enabled);
    }

    /**
     * Resets the state of the panel internal logics and UI elements, so that<br>
     * it becomes in the initial state to be used again.<br>
     * Usually used after stopClock().
     */
    public void resetClock() {
        clockLabel.setText("00:00:00");
        amountLabel.setText("0.00");
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        numberParticipantsLabel = new JLabel();
        payRateLabel = new JLabel();
        numberParticipantsTextField = new javax.swing.JTextField();
        payRateTextField = new javax.swing.JTextField();
        startButton = new javax.swing.JButton();
        pauseButton = new javax.swing.JButton();
        timerNameLabel = new JLabel();
        amountNameLabel = new JLabel();
        clockLabel = new JLabel();
        amountLabel = new JLabel();

        numberParticipantsLabel.setText("Number of participants: ");

        payRateLabel.setText("Pay rate per hour: ");

        numberParticipantsTextField.setText("0");

        payRateTextField.setText("0.00");

        //TODO think about split to 2 buttons - start and stop
        startButton.setText("START");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        pauseButton.setText("PAUSE");
        pauseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                presenter.pauseButtonActionPerformed();
            }
        });

        timerNameLabel.setText("Timer: ");

        amountNameLabel.setText("Amount: ");

        clockLabel.setText("00:00:00");

        amountLabel.setText("0.00");

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
                mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(mainPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(mainPanelLayout.createSequentialGroup()
                                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, mainPanelLayout.createSequentialGroup()
                                                                .addGap(23, 23, 23)
                                                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(mainPanelLayout.createSequentialGroup()
                                                                                .addComponent(startButton)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                                                                                .addComponent(pauseButton))
                                                                        .addGroup(mainPanelLayout.createSequentialGroup()
                                                                                .addGap(11, 11, 11)
                                                                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                        .addComponent(timerNameLabel)
                                                                                        .addComponent(clockLabel)))))
                                                        .addGroup(mainPanelLayout.createSequentialGroup()
                                                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(numberParticipantsLabel)
                                                                        .addComponent(payRateLabel))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, mainPanelLayout.createSequentialGroup()
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                                                                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                                        .addGroup(mainPanelLayout.createSequentialGroup()
                                                                                                .addGap(10, 10, 10)
                                                                                                .addComponent(amountLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                                                        .addComponent(amountNameLabel, javax.swing.GroupLayout.Alignment.TRAILING)))
                                                                        .addComponent(payRateTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                                                        .addComponent(numberParticipantsTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))))
                                                .addGap(24, 24, 24))))
        );
        mainPanelLayout.setVerticalGroup(
                mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(mainPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(numberParticipantsLabel)
                                        .addComponent(numberParticipantsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(payRateLabel)
                                        .addComponent(payRateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(startButton)
                                        .addComponent(pauseButton))
                                .addGap(18, 18, 18)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(amountNameLabel)
                                        .addComponent(timerNameLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(amountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(clockLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * The actions that are done when the "START/"STOP" button is clicked.<br>
     * They depend on the current state of the clock - PAUSED/RUNNING/STOPPED.
     *
     * @param evt
     */
    //TODO most tricky method here! carefully should be refactored and being dependant on fewer booleans
    //TODO move to presenter
    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        if (presenter.isClockTicking()) { //if true, the button says STOP
            if (askIfWantToAbort()) {
                presenter.resumeIfPaused();

                setInput(true);
                presenter.stopClock();
                if (wantsReport()) {
                    presenter.showResultsPage(this);
                }
                presenter.resetClock();
            }
        } else { //if false, the button says START
            boolean isInputValid = presenter.validateInput(
                    numberParticipantsTextField.getText(),
                    payRateTextField.getText()
            );

            if (isInputValid) {
                setInput(false);
                presenter.startClock();
            }
        }
    }//GEN-LAST:event_startButtonActionPerformed

    // Vardiables declaration - do not modify//GEN-BEGIN:variables
    private JLabel amountLabel;
    private JLabel amountNameLabel;
    private JLabel clockLabel;
    private javax.swing.JPanel mainPanel;
    private JLabel numberParticipantsLabel;
    private javax.swing.JTextField numberParticipantsTextField;
    private javax.swing.JButton pauseButton;
    private JLabel payRateLabel;
    private javax.swing.JTextField payRateTextField;
    private javax.swing.JButton startButton;
    private JLabel timerNameLabel;

    @Override
    public void setClock(String formattedTimer) {
        clockLabel.setText(formattedTimer);
    }

    @Override
    public void setAmount(String formattedAmount) {
        amountLabel.setText(formattedAmount);
    }
}
